### ISSUE TITLE
False UnbalancedError 

### ISSUE THREAD

**Issue by Glazz87** [eentzel/htmltruncate.py#7]
You wrote great module thanks you!
But it seems little bug.

```
>>> htmltruncate.truncate('фывафдывфдлсв<br><strong>фыварфылвр </strong><br>ываыва<br><br><em>ываываыавфв</em><br><br><br><strong>вфвфывфыв<br><br><img class="img-responsive" src="/files/076e3caed758a1c18c91a0e9cae3368f.jpg"><br><br>fdfgdfg<br>sdfsdfsf<em>sdfsfdsfs
df</em></strong><br><ol><li><strong><em>aasd</em></strong></li></ol>', 50)
'фывафдывфдлсв<br><strong>фыварфылвр\xa0</strong><br>ываыва<br><br><em>ываываыавфв</em><br><br><br><strong>вфвфывфыв</strong></br></br></br></br></br></br></br>'
>>>
>>> htmltruncate.truncate('фывафдывфдлсв<br><strong>фыварфылвр </strong><br>ываыва<br><br><em>ываываыавфв</em><br><br><br><strong>вфвфывфыв<br><br><img class="img-responsive" src="/files/076e3caed758a1c18c91a0e9cae3368f.jpg"><br><br>fdfgdfg<br>sdfsdfsf<em>sdfsfdsfs
df</em></strong><br><ol><li><strong><em>aasd</em></strong></li></ol>', 200)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\GitLab\personal\exp_14\app\htmltruncate.py", line 143, in truncate
    raise UnbalancedError( tok.as_string() )
htmltruncate.UnbalancedError: </strong>
>>>
```

If I replace `<img>` tag with same but closing `<img />` then the problem disappears.

**Comment by eentzel** [comment]
The library currently requires (like XHTML) that self-closing tags[1] have
the trailing slash. I think we could add a list of HTML5 void-elements[2]
so that it "knows" that tags like <img> are self-closing.

[1] http://xahlee.info/js/html5_non-closing_tag.html
[2] https://html.spec.whatwg.org/multipage/syntax.html#void-elements
